### PR TITLE
HTML Element Mapping

### PR DESCRIPTION
**Pull request by gunjankothari**

### CODE REVIEW

**Comment by bluerssen** [comment]
- Rename file from Elements to HtmlElements
- We need to add to the Index so they are exported, right?
- I dont think `BLOCK_STYLES_SECTIONS` is sufficient here, because most of these are text elements that need typography, so for those text elements we should provide the same as text components. 
-

**Review by bluerssen — CHANGES_REQUESTED** [review]
See my other comment

**Comment by bluerssen** [comment]
Ready to be merged when @adnelson fixes bug re: mappings without props

**Review by bluerssen — APPROVED** [review]

**Comment by YoussefHenna** [comment]
Closed in favor of https://github.com/draftbit/react-native-jigsaw/pull/591

**Pull request closed without merging**
