### PR TITLE
Added webview

### PR DESCRIPTION
**Pull request by YoussefHenna**
added webview using both https://github.com/react-native-webview/react-native-webview & https://github.com/react-native-web-community/react-native-web-webview

Webpack needs to be configured for it to work though, see the changes in the example app.

### CODE REVIEW

**Comment by peterpme** [comment]
Was this working for you on the web? I get this error: 
image

**Comment by peterpme** [comment]
I was taking a look at Expo AV and how they handle createElement, you might have to do something like this:

```
import createElement from 'react-native-web/dist/exports/createElement';
```

https://github.com/expo/expo/blob/master/packages/expo-av/src/ExponentVideo.web.tsx

**Comment by YoussefHenna** [comment]
It was working for me. Will take a second look, maybe I missed something

**Comment by YoussefHenna** [comment]
It works for me on web and android. Here is a screenshot from web. The same error your getting I got when webpack wasn't configured correctly, so make sure it matches and try again.
Screenshot_1

**Pull request closed without merging**
