### PR TITLE
P-3128 Dateepicker font color

### PR DESCRIPTION
**Pull request by gunjankothari**

### CODE REVIEW

**Comment by bluerssen** [comment]
@gunjankothari I think we need correlated stylesPanelSections in the mappings file.

**Comment by bluerssen** [comment]
@gunjankothari This is close. 

Screen Shot 2022-11-18 at 9 47 20 AM


Needs the following additions/fixes:
- For the labels (ie "Date") and any text that appears below, etc -- have it use the same font family. 
- Create a new config sizing props for any of the labels, additional text. ie "Label Size"
- Create a new config color prop for any of the labels, ie "Label Color"
- Create a new config color prop for the underline / border around the field (as shown in the image)

**Review by bluerssen — CHANGES_REQUESTED** [review]
See comment

**Comment by gunjankothari** [comment]
> See comment

Ready for review

**Comment by bluerssen** [comment]
@gunjankothari Can you fix the listing errors? See the failing check.

**Pull request closed without merging**
