### PR TITLE
Adjust height + padding for picker component

### PR DESCRIPTION
**Pull request by sieu-db**
## Overview
- Support custom smaller size for picker component

Screenshot 2024-08-07 at 06 16 40

### CODE REVIEW

**Review by YoussefHenna — CHANGES_REQUESTED** [review]
image

image

Seems there's some issue with spacing on the default sized picker

**Comment by sieu-db** [comment]
> image
> 
> image
> 
> Seems there's some issue with spacing on the default sized picker

How to reproduce this one, Is it just add leftIconName in example @YoussefHenna ?

**Comment by YoussefHenna** [comment]
> How to reproduce this one, Is it just add leftIconName in example @YoussefHenna ? I try but it also happen on "master" branch also

I was able to reproduce on master as well. Seems the issue comes when leftIconMode is not provided. Once you give it a value of `inset` or `outset`, it works as expected. It's not an issue from your work here, but maybe you can add a default value on TextField component for `leftIconMode = "inset"`.

**Review by YoussefHenna — APPROVED** [review]

**Comment by sieu-db** [comment]
> > How to reproduce this one, Is it just add leftIconName in example @YoussefHenna ? I try but it also happen on "master" branch also
> 
> I was able to reproduce on master as well. Seems the issue comes when leftIconMode is not provided. Once you give it a value of `inset` or `outset`, it works as expected. It's not an issue from your work here, but maybe you can add a default value on TextField component for `leftIconMode = "inset"`.

Got it, I'm added this one then we can merge this 🙏

**Pull request merged**
