### PR TITLE
Add Expo Image

### PR DESCRIPTION
**Pull request by bluerssen**

### CODE REVIEW

**Comment by YoussefHenna** [comment]
Closing in favor of https://github.com/draftbit/react-native-jigsaw/pull/589 (same changes for merge in 46 branch)

**Comment by YoussefHenna** [comment]
Reopened due to expo-image being v47+

**Comment by bluerssen** [comment]
@YoussefHenna can you update this for 47?

**Comment by YoussefHenna** [comment]
Will do. https://linear.app/draftbit/issue/P-3479/add-expo-image

**Comment by bluerssen** [comment]
@YoussefHenna if you want to recreate / update this for expo 48 that would be great.

**Comment by YoussefHenna** [comment]
Superceeded with https://github.com/draftbit/react-native-jigsaw/pull/968

**Pull request closed without merging**
