### PR TITLE
P-2586 Youtube Component

### PR DESCRIPTION
**Pull request by gunjankothari**

### CODE REVIEW

**Comment by dsebek** [comment]
@bluerssen I have a working custom definition of a youtube component that could be easily repurposed if needed lmk

**Comment by bluerssen** [comment]
maybe post the code or link to code here? I think Gunjan is going to update this next week, but if you have soething already please update this PR or post to the details to save time!

Brian

**Comment by bluerssen** [comment]
I'm not sure this will work with this package, because `react-native-web-webview` is super old and likely conflicts.

**Comment by bluerssen** [comment]
https://www.npmjs.com/package/react_native_youtube_streamer

**Comment by YoussefHenna** [comment]
Closed in favor of https://github.com/draftbit/react-native-jigsaw/pull/596

**Pull request closed without merging**
