### PR TITLE
P-2565 Markdown Component

### PR DESCRIPTION
**Pull request by gunjankothari**

### CODE REVIEW

**Comment by gunjankothari** [comment]
Note - The library used for this component is not maintained anymore. It also has some typescript errors with the library. We should look for a better library.

**Comment by bluerssen** [comment]
@gunjankothari what about https://github.com/andangrd/react-native-markdown-package#readme

**Comment by bluerssen** [comment]
This package doesnt work in snack as far as I can tell: https://snack.expo.dev/@briandraftbit/intrigued-celery

**Comment by YoussefHenna** [comment]
Closing in favor https://github.com/draftbit/react-native-jigsaw/pull/597

**Pull request closed without merging**
